services:
  - type: web
    name: EstoqueCdg
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn systemestoque.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key

