# Generated by Django 5.2.6 on 2025-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0002_auto_20241227_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
