# Generated by Django 2.2 on 2025-01-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_auto_20241227_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Empresa'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
