# Generated by Django 5.2.6 on 2025-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_auto_20250109_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
