# Generated by Django 3.2.25 on 2024-12-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0001_initial'),
        ('produto', '0004_rename_estoquemin_produto_estoquemin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formato.formato'),
        ),
    ]
