# Generated by Django 3.2.25 on 2024-12-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0001_initial'),
        ('produto', '0005_alter_produto_id_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='formato',
            field=models.CharField(choices=[('null', 'null'), ('640x880', '640x880'), ('660x960', '660x960')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_formato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formato.formato'),
            preserve_default=False,
        ),
    ]
