# Generated by Django 3.2.25 on 2024-12-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formato', '0001_initial'),
        ('produto', '0007_auto_20241220_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_formato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formato.formato'),
            preserve_default=False,
        ),
    ]
