# Generated by Django 2.2 on 2024-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_produto_id_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
