# Generated by Django 2.2 on 2025-01-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20241227_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formato.Formato'),
        ),
    ]
