# Generated by Django 2.2 on 2025-01-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_auto_20250109_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estoques', to='produto.Produto'),
        ),
    ]
